### ISSUE TITLE
⚠️ I will (propably) break soon.

### ISSUE THREAD

**Issue by RienNeVaPlus** [RienNeVaPlus/wikifolio#15]
A few days ago, wikifolio announced a relaunch, which is highly likely to break this API - please be warned.

I will try to fix things, but there will be a delay, as this is a side project of my free time.
Pull requests are always welcome.

**Comment by wemakefuture** [comment]
Yes it broke. Error message is

"login failed, Cookie not found"

**Comment by jekru** [comment]
> Yes it broke. Error message is
> 
> "login failed, Cookie not found"

See #18. If @RienNeVaPlus updates the npm package, it should work again.

**Comment by RienNeVaPlus** [comment]
v0.4.2 published. But there's more broken. I miss the old layout.

**Comment by wemakefuture** [comment]
@RienNeVaPlus yeah - the old layout was smooth. Getting the trades is currently not working, patched 0.4.2. 

Trying to grab the trades ends with a:
`[-] No trades found.`

**Comment by jekru** [comment]
> @RienNeVaPlus yeah - the old layout was smooth. Getting the trades is currently not working, patched 0.4.2.
> 
> Trying to grab the trades ends with a: `[-] No trades found.`

Could you provide more details? And are you sure that the wikifolio has any trades? Because fetching wikifolio trades is working for me.

```ts
const api = new Api({email: '', password: ''});
const wikifolio = api.wikifolio('');
const trades = await wikifolio.trades();

console.log(trades);
```

**Comment by farhan-gif** [comment]
Hello, thanks for providing the api! 
After the website upgrade, is the buy/sell function working for you guys? I get the below error for buy/sell
Error: Wikifolio JSON not found. This is probably a bug, please report it.
    at Wikifolio.<anonymous> (C:\wikifolio\node_modules\wikifolio\dist\models\Wikifolio.js:294:35)
    at step (C:\wikifolio\node_modules\wikifolio\dist\models\Wikifolio.js:44:23)
    at Object.next (C:\wikifolio\node_modules\wikifolio\dist\models\Wikifolio.js:25:53)
    at fulfilled (C:\wikifolio\node_modules\wikifolio\dist\models\Wikifolio.js:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Any help would be much appreciated

**Comment by henrydatei** [comment]
> Hello, thanks for providing the api! After the website upgrade, is the buy/sell function working for you guys? I get the below error for buy/sell Error: Wikifolio JSON not found. This is probably a bug, please report it. at Wikifolio. (C:\wikifolio\node_modules\wikifolio\dist\models\Wikifolio.js:294:35) at step (C:\wikifolio\node_modules\wikifolio\dist\models\Wikifolio.js:44:23) at Object.next (C:\wikifolio\node_modules\wikifolio\dist\models\Wikifolio.js:25:53) at fulfilled (C:\wikifolio\node_modules\wikifolio\dist\models\Wikifolio.js:16:58) at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
> Any help would be much appreciated

I get the same error on other functions, see #19

**Comment by jekru** [comment]
I am currently debugging (and fixing) **Wikifolio.ts**. I already created a (draft) PR #20. If anyone wants to join me, let me know :)

**Comment by Tires** [comment]
Any news since 2022?
