### ISSUE TITLE
Order cannot be placed

### ISSUE THREAD

**Issue by JulianSchl** [RienNeVaPlus/wikifolio#6]
Hi,

I'm facing the following issue while executing an order:
```
Your credentials will not be stored.
2021-09-17T00:00:00.000Z
(node:2593) UnhandledPromiseRejectionWarning: Error: Unable to submit order (Bei Limit- oder Stoplimitorders muss das Gültigkeitsdatum angegeben werden.)
    at Order.<anonymous> (/home/julian/experiments/nodejs/projects/wikifolio/wikifolio-example/node_modules/wikifolio/dist/models/Order.js:151:35)
    at step (/home/julian/experiments/nodejs/projects/wikifolio/wikifolio-example/node_modules/wikifolio/dist/models/Order.js:44:23)
    at Object.next (/home/julian/experiments/nodejs/projects/wikifolio/wikifolio-example/node_modules/wikifolio/dist/models/Order.js:25:53)
    at fulfilled (/home/julian/experiments/nodejs/projects/wikifolio/wikifolio-example/node_modules/wikifolio/dist/models/Order.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2593) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2593) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I did pass the same timestamp as the api does, when placing an order in the browser.

**Comment by RienNeVaPlus** [comment]
How did you pass the timestamp? It should be a `Date` or an ISO formatted `string`:

```ts
export interface OrderParam {
	amount: number
	limitPrice: number,
	orderType: OrderType,
	stopLossLimitPrice?: number,
	stopLossStopPrice?: number,
	stopPrice?: number,
	takeProfitLimitPrice?: number | null,
	underlyingIsin: string,
	expiresAt: Date | string
}
```

**Comment by JulianSchl** [comment]
I passed it like you did in your Readme.md as string via `validUntil`. And I just took the value the Browser would send to the API so I don't think it is a formatting issue.

**Comment by RienNeVaPlus** [comment]
The readme might be wrong, try passing the date via `expiresAt`. I can try to reproduce it by next week, if that doesn't work.
